name: module-storage-account
concurrency: module-storage-account

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'modules/storage-account/**'
      - 'modules/storage-account/*'
      - 'modules/*'

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: storage-account
  MODULE_REGISTRY_SERVER: bicepmol.azurecr.io
  MODULE_FILE_PATH: modules/storage-account/main.bicep
  MODULE_METADATA_FILE_PATH: modules/storage-account/metadata.json

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Run Bicep linter
        run: az bicep build --file ${{ env.MODULE_FILE_PATH }}
    
    publish:
      runs-on: ubuntu-latest
      needs: [ lint ]
      steps:
      - uses: actions/checkout@v3.3.0
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Get module version number
        run: |
          majorMinorVersionNumber=$(jq '(.version.major | tostring) + "." + (.version.minor | tostring)' ${{ env.MODULE_METADATA_FILE_PATH }} -r )
          echo $majorMinorVersionNumber
          echo ${{ env.MODULE_FILE_PATH }}
          echo ${{ env.MODULE_REGISTRY_SERVER }}
          echo ${{ env.MODULE_NAME }}
          versionNumber="$majorMinorVersionNumber.${{ github.run_number }}"
          echo "MODULE_VERSION=$versionNumber" >> $GITHUB_ENV     
          echo ${{ env.MODULE_VERSION }}
      - uses: azure/cli@v1
        name: Publish module
        with:
          azcliversion: 2.45.0
          inlineScript: |
            ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
            az bicep publish --file modules/storage-account/main.bicep --target br:${{ env.MODULE_REGISTRY_SERVER }}/${{ env.MODULE_NAME }}:${{ env.MODULE_VERSION }}
                      
